product:
  name: Red Hat Fuse
  abbreviation: Fuse-and-FIS
  stage: ${build.milestone}
  issueTrackerUrl: http://issues.jboss.org/browse/ENTESB
version: ${version.fuse.prefix}
milestone: ${build.milestone}
group: Red Hat Fuse - Base ${version.fuse.project} ${build.milestone}
defaultBuildParameters:
  environmentId: 8
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false clean
    deploy'

builds:
- name: cxf-3.3.3-${version.fuse.prefix}
  project: jboss-fuse/cxf
    #fetchScmUrl: git%40github.com%3Ajboss-fuse%2Fcxf.git
    #pushScmUrl: git%40github.com%3Ajboss-fuse%2Fcxf.git
    #tag: cxf-${version.cxf}
    #buildCommand: ${cxf.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/cxf.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/cxf.git
  scmRevision: cxf-${version.cxf}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  customPmeParameters:
    - ${cxf.pme.options}
  buildPodMemory: 8
  buildScript: >
    mvn -e -V -B -DskipTests -Dassembly.tarLongFileMode=posix -DfailIfNoTests=false -Dtest=false -Dcxf.public.suffix.list.url=http://dev138.mw.lab.eng.bos.redhat.com/miscellaneous/effective_tld_names.dat -Pdeploy clean deploy

- name: camel-3.0.0-${version.fuse.prefix}
  project: jboss-fuse/camel
    #fetchScmUrl: ${camel.fetch.scmUrl}
    #pushScmUrl: ${camel.push.scmUrl}
    #tag: camel-${version.camel}
    #buildCommand: ${camel.buildCommand}
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/camel.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/camel.git
  scmRevision: camel-${version.camel}
  pigYamlMetadata: Fuse dev build ${build.url} Fuse ${yaml.name} yaml config ${project.version}
  buildPodMemory: 12
  buildScript: >
    export JAVA_TOOL_OPTIONS=\"-Xmx3g\"

    export MAVEN_OPTS=\"-Xmx4g\"

    mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -Penable-schemagen,release,apt
    clean deploy -DkeepStagingRepositoryOnCloseRuleFailure=true -Dgpg.skip=true -pl
    '!org.apache.camel:camel-itest,!org.apache.camel.example:camel-example-swagger-xml'
  customPmeParameters:
    - ${camel.pme.options}
  extraRepositories:
    - http://resources.knopflerfish.org/repo/maven2/release/
  dependencies:
  - cxf-3.3.3-${version.fuse.prefix}

outputPrefixes:
  releaseFile: fuse-test
  releaseDir: fuse-test
flow:
  #licensesGeneration: gen.downloadFrom 'karaf' matching '.*license\.zip'
  #licensesGeneration: gen.generate()
  #repositoryGeneration: gen.downloadFrom 'karaf' matching '.*-m2repo\.zip'
  #javadocGeneration: gen.downloadFrom 'karaf' matching '.*javadoc\.zip'
  #addons:
  #runtimeDependenciesAnalyzer:
  #  downloadFrom: 'WildFly-Swarm'
  #  matching: '.*runtime-dependencies\.zip'
  #  referenceBuild: 'WildFly-Swarm'
