product:
  name: Red Hat Fuse
  abbreviation: Fuse-and-FIS
  stage: EA
  issueTrackerUrl: http://issues.jboss.org/browse/ENTESB
version: ${version.fuse.prefix}
milestone: EA
group: Fuse Staging Standalone and FIS 7.3
defaultBuildParameters:
  environmentId: 1
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false clean
    deploy'

builds:
- name: cxf-xjc-utils-3.2.4-${version.fuse.prefix}
  project: jboss-fuse/cxf-xjc-utils
    #fetchScmUrl: ${cxf-xjc-utils.fetch.scmUrl}
    #pushScmUrl: ${cxf-xjc-utils.push.scmUrl}
    #tag: ${cxf-xjc-utils.tag}
    #buildCommand: ${cxf-xjc-utils.buildCommand}
  scmUrl: git+ssh://code.stage.engineering.redhat.com/jboss-fuse/cxf-xjc-utils.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/cxf-xjc-utils.git
  buildScript: >
    mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false 
    -Dcheckstyle.skip=true clean deploy
  scmRevision: cxf-xjc-utils-${version.cxf.xjc-utils}

- name: karaf-4.2.0-${version.fuse.prefix}
  project: jboss-fuse/karaf
    #fetchScmUrl: ${karaf.fetch.scmUrl}
    #pushScmUrl: ${karaf.push.scmUrl}
    #tag: ${karaf.tag}
    #buildCommand: ${karaf.buildCommand}
  scmUrl: git+ssh://code.stage.engineering.redhat.com/jboss-fuse/karaf.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/karaf.git
  scmRevision: karaf-${version.karaf}
  customPmeParameters:
  - '-DdependencyOverride.com.sun.xml.bind:*@*=2.2.11.redhat-4'
  - '-DdependencyOverride.org.ow2.asm:*@*='
  - '-DprojectMetaSkip=true'

- name: kubernetes-model-2.0.10-7.3.0
  project: jboss-fuse/kubernetes-model
    #fetchScmUrl: ${kubernetes-model.fetch.scmUrl}
    #pushScmUrl: ${kubernetes-model.push.scmUrl}
    #tag: ${kubernetes-model.tag}
    #buildCommand: ${kubernetes-model.buildCommand}
  scmUrl: git+ssh://code.stage.engineering.redhat.com/jboss-fuse/kubernetes-model.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/kubernetes-model.git
  buildScript: 'mvn -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -P clean deploy'
  scmRevision: kubernetes-model-${version.kubernetes.model}

- name: kubernetes-client-3.1.12-7.3.0
  project: jboss-fuse/kubernetes-client
    #fetchScmUrl: ${kubernetes-client.fetch.scmUrl}
    #pushScmUrl: ${kubernetes-client.push.scmUrl}
    #tag: ${kubernetes-client.tag}
    #buildCommand: ${kubernetes-client.buildCommand}
  scmUrl: git+ssh://code.stage.engineering.redhat.com/jboss-fuse/kubernetes-client.git
  externalScmUrl: ssh://git@github.com/jboss-fuse/kubernetes-client.git
  scmRevision: kubernetes-client-${version.kubernetes.client}
  customPmeParameters:
    - '-DprojectMetaSkip=true'
    - '-DdependencyExclusion.com.fasterxml.jackson.core:*@*='
    - '-DdependencyExclusion.com.fasterxml.jackson.module:*@*='
    - '-DdependencyExclusion.com.fasterxml.jackson.dataformat:*@*='
  dependencies:
  - kubernetes-model-2.0.10-7.3.0

- name: cxf-3.2.7-7.3.0
  project: jboss-fuse/cxf
    #fetchScmUrl: git%40github.com%3Ajboss-fuse%2Fcxf.git
    #pushScmUrl: git%40github.com%3Ajboss-fuse%2Fcxf.git
    #tag: 3.2.x.redhat-7-x
    #buildCommand: 1
  scmUrl: git+ssh://code.engineering.redhat.com/jboss-fuse/cxf.git
  scmRevision: cxf-3.2.7.fuse-730021
  customPmeParameters:
    - '-DdependencyOverride.org.codehaus.woodstox:*@*='
    - '-DdependencyOverride.org.apache.abdera:*@*='
    - '-DdependencyOverride.javax.annotation:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.module:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.jaxrs:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.core:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.jaxrs:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.dataformat:*@*='
    - '-DdependencyOverride.com.fasterxml.jackson.datatype:*@*='
    - '-DdependencyOverride.org.bouncycastle:*@*='
    - '-DprojectMetaSkip=true'
  buildScript: 'mvn  -e -V -B -DskipTests -DfailIfNoTests=false -Dtest=false -Dcxf.public.suffix.list.url=http://dev138.mw.lab.eng.bos.redhat.com/miscellaneous/effective_tld_names.dat
    -Pdeploy clean deploy'
  dependencies:
  - cxf-xjc-utils-3.2.4-7.3.0
  - karaf-4.2.0-7.3.0

outputPrefixes:
  releaseFile: fuse-test
  releaseDir: fuse-test
flow:
  #licensesGeneration: gen.downloadFrom 'karaf' matching '.*license\.zip'
  #licensesGeneration: gen.generate()
  #repositoryGeneration: gen.downloadFrom 'karaf' matching '.*-m2repo\.zip'
  #javadocGeneration: gen.downloadFrom 'karaf' matching '.*javadoc\.zip'
  #addons:
  #runtimeDependenciesAnalyzer:
  #  downloadFrom: 'WildFly-Swarm'
  #  matching: '.*runtime-dependencies\.zip'
  #  referenceBuild: 'WildFly-Swarm'
